from backend.extensions import db
from .users_model import User
from .platforms_model import Platform
from .notification_models_model import NotificationPlatform
from .notifications_model import Notification
from .models_model import Model
from .logs_model import Log
from .devices_model import Device
from .log_bboxes_model import LogBBox 
from .user_platforms_model import UserPlatform
